version: "3.7"

services:
  db:
    image: postgres:12.1-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  aiohttp-pg:
    image: aiohttp-pg
    build: .
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=aiohttp_crud
    depends_on:
      - db
  ci:
    image: aiohttp-pg
    build: .
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=aiohttp_crud_test
    depends_on:
      - db
    entrypoint: /repo/files/run_tests.sh